In [3]:
import numpy as np
import math

In [3]:
# Declaring an array (or single row matrix) with 3 items in a list
a = np.array([1,2,3])
print(a)
print(a.ndim) # The # of dimensions the array has

[1 2 3]
1


In [31]:
# Return number of dimension of an array (1D and 2D is most likely what i'll be using)
b = np.array([[1,3],[4,5],[5,8]])
print(b.ndim)

[[1 3]
 [4 5]
 [5 8]]
2


In [32]:
# Number of rows by number of columns
b.shape 

(3, 2)

In [7]:
a.dtype

dtype('int64')

In [8]:
c = np.array([2.2,2.4])
c.dtype.name

'float64'

In [10]:
# Creating array size placeholders

# Creates array filled with zeros
d = np.zeros((2,3))
print()
print(d)

# Fills array with ones
e = np.ones((2,3))
print(e)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [33]:
# random numbers filled in an array

# rand(number_of_rows,number_of_columns)
np.random.rand(4,5)

array([[0.18276555, 0.71334898, 0.81268889, 0.71270097, 0.52969618],
       [0.0088931 , 0.5435837 , 0.30844348, 0.61249541, 0.30450969],
       [0.81122156, 0.18116219, 0.34928925, 0.38037177, 0.58245853],
       [0.48327732, 0.48101196, 0.01710397, 0.60077723, 0.2528359 ]])

In [13]:
# Create an array of every even number from ten inclusive to fifty exclusive
f = np.arange(10,50,2)
f

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

In [15]:
# generating an evenly spaced set of floats between a specific range, where the third parameter 
# defines how many items you want in an array
np.linspace(0,4,8)

array([0.        , 0.57142857, 1.14285714, 1.71428571, 2.28571429,
       2.85714286, 3.42857143, 4.        ])

Array Operations

In [16]:
# Arithmetic operators on array apply alementwise
a = np.array([10,20,30,40])
b = np.array([1,2,3,4])

# Subtracts each element from list b from list a, with matching indexes
c = a-b
print(c)

d = a*b
print(d)

[ 9 18 27 36]
[ 10  40  90 160]


In [35]:
# An applied example of using arithmetic formulas on arrays in an iterative manner
farenheit = np.array([0,-10,-5,-15,0])

celcius = (farenheit - 31)*(5/9)
print(celcius)

[-17.22222222 -22.77777778 -20.         -25.55555556 -17.22222222]


In [36]:
# You can provide boolean responses for an array to scan if a specific logical expression is met
print(celcius > -21)
# This is called elementwise manipulation

[ True False  True False  True]


In [21]:
# Numpy also supports matrix manipulation
# dot product of matrices is denoted via the @ sign

A = np.array([[1,2],[0,3]])
B = np.array([[1,4],[3,4]])

print(A@B)

[[ 7 12]
 [ 9 12]]


In [22]:
# Check shape of matrices
A.shape
B.shape

(2, 2)

Indexing, Slicing and Iterating

Integer Indexing

In [23]:
a = np.array([1,2,4,5])

In [24]:
a[2]

4

In [25]:
a = np.array([[1,3],[4,5],[4,9]])
a

array([[1, 3],
       [4, 5],
       [4, 9]])

In [26]:
# Returns item at index [1,1]
a[1,1]

5

Boolean Indexing

In [27]:
print(a>3)

[[False False]
 [ True  True]
 [ True  True]]


In [28]:
# Returns an array with all values which are greater than 3 in the multi dimensional 
# matrix
# this is called boolean masking

print(a[a>3])

[4 5 4 9]


Slicing

In [37]:
# Slicing for multiple dimensional arrays
a = np.array([[1,3,5],[4,5,6],[8,8,8]])

In [38]:
a

array([[1, 3, 5],
       [4, 5, 6],
       [8, 8, 8]])

In [39]:
# Displays first two rows
a[:2]

array([[1, 3, 5],
       [4, 5, 6]])

In [41]:
# Returns first row, and columns 1-2 @ indeces 1/2
a[:1,1:3]

array([[3, 5]])

In [46]:
# Multidimensional arrays, the first argument is for selecting rows and the second argument
# is for selecting columns
import pandas as pd

df = pd.read_csv('kobe_shot_selection.csv')
print(df)

             action_type combined_shot_type  game_event_id   game_id      lat  \
0              Jump Shot          Jump Shot             10  20000012  33.9723   
1              Jump Shot          Jump Shot             12  20000012  34.0443   
2              Jump Shot          Jump Shot             35  20000012  33.9093   
3              Jump Shot          Jump Shot             43  20000012  33.8693   
4      Driving Dunk Shot               Dunk            155  20000012  34.0443   
...                  ...                ...            ...       ...      ...   
30692          Jump Shot          Jump Shot            397  49900088  33.9963   
30693           Tip Shot           Tip Shot            398  49900088  34.0443   
30694  Running Jump Shot          Jump Shot            426  49900088  33.8783   
30695          Jump Shot          Jump Shot            448  49900088  33.7773   
30696          Jump Shot          Jump Shot            471  49900088  33.9723   

       loc_x  loc_y       l

In [12]:
# Create a generated array (single dimension), and reshape to 3x5
arranged_array = np.arange(1,16,1).reshape(3,5)
arranged_array

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [1]:
dollars = 3.45
tax = 0.5
tax_in_cents = [dollars*tax]
tax_in_cents

[1.725]

In [3]:
dollar_amount = 24.24
tax_rate = 0.06
tax_amount = [dollar_amount*tax_rate]
tax_amount

[1.4544]

In [15]:
import random

deck =['A',1,2,3,4,5,6,7,8,9,10,'J','K','Q']

def shuffle_deck(deck):
    shuffled_deck =[]
    i = 0
    while i in range(0,len(deck)):
        shuffled_deck.append(deck[random.randint(0,len(deck)-1)])
        i +=1
    return shuffled_deck


shuffle_deck(deck)
    


['A', 'J', 'K', 'A', 7, 'K', 'K', 'Q', 10, 6, 'Q', 5, 'J', 1]